name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test
        run: npm test

      - name: Typecheck
        run: npm run typecheck

  generate:
    name: Generate
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      BRANCH: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Generate Fallow Badge
        run: npm run gen:fallow-badge

      - name: Check for Changes
        id: check_changes
        run: |
          if [[ -n "$(git diff --exit-code)" ]]; then
            echo "Changes detected."
            echo "::set-output name=has_changes::true"
          else
            echo "No changes detected."
            echo "::set-output name=has_changes::false"
          fi

      - name: Commit
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git add -A
          git commit -m "chore: update generated files [skip ci]"
          git push origin HEAD:${{ env.BRANCH }} --no-verify

  code-style:
    name: Code Style
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Format
        run: npm run format:check

      - name: Lint
        run: npm run lint

  prerelease:
    name: Prerelease
    needs: [test, code-style]
    if: github.event_name == 'push'
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      release: prerelease
