name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release type'
        required: true
        default: prerelease
        type: choice
        options:
          - prerelease
          - prepatch
          - preminor
          - premajor
          - patch
          - minor
          - major
  push:
    branches: main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: validate
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        id: setup
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Pre-Release
        if: inputs.release == 'preminor' || inputs.release == 'prepatch' || inputs.release == 'prerelease' || inputs.release == 'premajor'
        run: npm run release -- ${{ inputs.release }} --ci --preRelease=beta --dry-run

      - name: Release
        if: inputs.release == 'patch' || inputs.release == 'minor' || inputs.release == 'major'
        run: npm run release -- ${{ inputs.release }} --ci --dry-run
