name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        default: prerelease
        description: 'Type'
        options:
          - prerelease
          - prepatch
          - preminor
          - premajor
          - patch
          - minor
          - major
        required: true
        type: choice
  push:
    branches: main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: validate
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        id: setup
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Beta Release
        if: contains(fromJSON('["premajor", "preminor", "prepatch", "prerelease"]'), inputs.release)
        run: npm run release -- ${{ inputs.release }} --ci --preRelease=beta --dry-run

      - name: Release
        if: contains(fromJSON('["major", "minor", "patch"]'), inputs.release)
        run: npm run release -- ${{ inputs.release }} --ci --dry-run
